import * as React from "react";
import * as Types from "../webflow_modules/types";

declare function ScrollingIcons(props: {
  icons113Icon1?: Types.Asset.Image;
  icons113Icon10?: Types.Asset.Image;
  icons113Icon10Visibility?: Types.Visibility.VisibilityConditions;
  icons113Icon11?: Types.Asset.Image;
  icons113Icon11Visibility?: Types.Visibility.VisibilityConditions;
  icons113Icon12?: Types.Asset.Image;
  icons113Icon12Visibility?: Types.Visibility.VisibilityConditions;
  icons113Icon13?: Types.Asset.Image;
  icons113Icon13Visibility?: Types.Visibility.VisibilityConditions;
  icons113Icon1Visibility?: Types.Visibility.VisibilityConditions;
  icons113Icon2?: Types.Asset.Image;
  icons113Icon2Visibility?: Types.Visibility.VisibilityConditions;
  icons113Icon3?: Types.Asset.Image;
  icons113Icon3Visibility?: Types.Visibility.VisibilityConditions;
  icons113Icon4?: Types.Asset.Image;
  icons113Icon4Visibility?: Types.Visibility.VisibilityConditions;
  icons113Icon5?: Types.Asset.Image;
  icons113Icon5Visibility?: Types.Visibility.VisibilityConditions;
  icons113Icon6?: Types.Asset.Image;
  icons113Icon6Visibility?: Types.Visibility.VisibilityConditions;
  icons113Icon7?: Types.Asset.Image;
  icons113Icon7Visibility?: Types.Visibility.VisibilityConditions;
  icons113Icon8?: Types.Asset.Image;
  icons113Icon8Visibility?: Types.Visibility.VisibilityConditions;
  icons113Icon9?: Types.Asset.Image;
  icons113Icon9Visibility?: Types.Visibility.VisibilityConditions;
  icons1423Icon14?: Types.Asset.Image;
  icons1423Icon14Visibility?: Types.Visibility.VisibilityConditions;
  icons1423Icon15Visibility?: Types.Visibility.VisibilityConditions;
  icons1423Icon16Visibility?: Types.Visibility.VisibilityConditions;
  icons1423Icon17Visibility?: Types.Visibility.VisibilityConditions;
  icons1423Icon18Visibility?: Types.Visibility.VisibilityConditions;
  icons1423Icon19Visibility?: Types.Visibility.VisibilityConditions;
  icons1423Icon20Visibility?: Types.Visibility.VisibilityConditions;
  sectionVisibility?: Types.Visibility.VisibilityConditions;
  settingsSectionId?: string;
}): React.JSX.Element;
