import * as React from "react";
import * as Types from "../webflow_modules/types";

declare function StrategyStackVerticalTabs(props: {
  mainSectionHeadlineSlot?: React.ReactNode;
  mainSectionMainParagraph?: React.ReactNode;
  mainTabsTab1Text?: React.ReactNode;
  mainTabsTab2Text?: React.ReactNode;
  mainTabsTab3Text?: React.ReactNode;
  mainTabsTab4Text?: React.ReactNode;
  settingsSectionId?: string;
  settingsSectionVisibility?: Types.Visibility.VisibilityConditions;
  tab1Button1Slot?: React.ReactNode;
  tab1Button2Slot?: React.ReactNode;
  tab1HeadlineTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  tab1HeadlineText?: React.ReactNode;
  tab1Item1?: React.ReactNode;
  tab1Item2?: React.ReactNode;
  tab1Item3?: React.ReactNode;
  tab1Item4?: React.ReactNode;
  tab1Item5?: React.ReactNode;
  tab1SubHeadlineText?: React.ReactNode;
  tab1TagSlot?: React.ReactNode;
  tab2Button1Slot?: React.ReactNode;
  tab2Button2Slot?: React.ReactNode;
  tab2HeadlineTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  tab2HeadlineText?: React.ReactNode;
  tab2Item1?: React.ReactNode;
  tab2Item2?: React.ReactNode;
  tab2Item3?: React.ReactNode;
  tab2Item4?: React.ReactNode;
  tab2Item5?: React.ReactNode;
  tab2SubHeadlineText?: React.ReactNode;
  tab2TagSlot?: React.ReactNode;
  tab3Button1Slot?: React.ReactNode;
  tab3Button2Slot?: React.ReactNode;
  tab3TagSlot?: React.ReactNode;
  tab4Button1Slot?: React.ReactNode;
  tab4Button2Slot?: React.ReactNode;
  tab4HeadlineTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  tab4HeadlineText?: React.ReactNode;
  tab4Item1?: React.ReactNode;
  tab4Item2?: React.ReactNode;
  tab4Item3?: React.ReactNode;
  tab4Item4?: React.ReactNode;
  tab4Item5?: React.ReactNode;
  tab4SubHeadlineText?: React.ReactNode;
  tab4TagSlot?: React.ReactNode;
  tag3HeadlineTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  tag3HeadlineText?: React.ReactNode;
  tag3Item1?: React.ReactNode;
  tag3Item2?: React.ReactNode;
  tag3Item3?: React.ReactNode;
  tag3Item4?: React.ReactNode;
  tag3Item5?: React.ReactNode;
  tag3SubHeadlineText?: React.ReactNode;
}): React.JSX.Element;
