import * as React from "react";
import * as Types from "../webflow_modules/types";

declare function DataSubjectAccessRequestForm(props: {
  checkbox1CheckboxLabel?: React.ReactNode;
  checkbox2CheckboxLabel?: React.ReactNode;
  checkbox3CheckboxLabel?: React.ReactNode;
  checkboxIcon1CheckboxIcon?: Types.Asset.Image;
  checkboxIcon1CheckboxIconAltText?: Types.Basic.AltText;
  checkboxIcon1CheckboxIconLabel?: React.ReactNode;
  checkboxIcon2CheckboxIcon?: Types.Asset.Image;
  checkboxIcon2CheckboxIconAltText?: Types.Basic.AltText;
  checkboxIcon2CheckboxIconLabel?: React.ReactNode;
  settingsFormId?: string;
  settingsFormVisibility?: Types.Visibility.VisibilityConditions;
  slide1Slide1Headline?: React.ReactNode;
  slide1SlideHeadlineTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  slide1SlideInputInstructions?: React.ReactNode;
  slide2DropDownInputDescription?: React.ReactNode;
  slide2SlideHeadlineTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  slide2SlideHeadlineText?: React.ReactNode;
  slide3Checkbox1Label?: React.ReactNode;
  slide3SlideHeadlineTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  slide3SlideHeadlineText?: React.ReactNode;
  slide4SlideDescription?: React.ReactNode;
  slide4SlideHeadlineTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  slide4SlideHeadlineText?: React.ReactNode;
  slide5SlideHeadlineTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  slide5SlideHeadlineText?: React.ReactNode;
  textInput1InputLabel?: React.ReactNode;
  textInput1TextInputId?: string;
  textInput1TextInputVisibility?: Types.Visibility.VisibilityConditions;
  textInput2InputLabel?: React.ReactNode;
  textInput2TextInputId?: string;
  textInput2TextInputVisibility?: Types.Visibility.VisibilityConditions;
  textInput3Checkbox2Label?: React.ReactNode;
  textInput3Checkbox3Label?: React.ReactNode;
  textInput3CheckboxInputDescription?: React.ReactNode;
  textInput3InputLabel?: React.ReactNode;
  textInput3MessageInputDescription?: React.ReactNode;
  textInput3TextInputId?: string;
  textInput3TextInputVisibility?: Types.Visibility.VisibilityConditions;
  textInput4InputLabel?: React.ReactNode;
  textInput4TextInputId?: string;
  textInput4TextInputVisibility?: Types.Visibility.VisibilityConditions;
  textInput5InputDescription?: React.ReactNode;
  textInput5TextInputId?: string;
  textInput5TextInputVisibility?: Types.Visibility.VisibilityConditions;
}): React.JSX.Element;
