import * as React from "react";
import * as Types from "../webflow_modules/types";

declare function ColorNavcardFullpage(props: {
  colorCard1HeadlineTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  colorCard1HeadlineText?: React.ReactNode;
  colorCard1Icon?: Types.Asset.Image;
  colorCard1IconAltText?: Types.Basic.AltText;
  colorCard1Image?: Types.Asset.Image;
  colorCard1ImageAltText?: Types.Basic.AltText;
  colorCard1Link?: Types.Basic.Link;
  colorCard1LinkText?: React.ReactNode;
  colorCard1Paragraph?: React.ReactNode;
  colorCard2HeadlineTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  colorCard2HeadlineText?: React.ReactNode;
  colorCard2Icon?: Types.Asset.Image;
  colorCard2IconAltText?: Types.Basic.AltText;
  colorCard2Image?: Types.Asset.Image;
  colorCard2ImageAltText?: Types.Basic.AltText;
  colorCard2Link?: Types.Basic.Link;
  colorCard2LinkText?: React.ReactNode;
  colorCard2Paragraph?: React.ReactNode;
  colorCard3HeadlineTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  colorCard3HeadlineText?: React.ReactNode;
  colorCard3Icon?: Types.Asset.Image;
  colorCard3IconAltText?: Types.Basic.AltText;
  colorCard3Image?: Types.Asset.Image;
  colorCard3ImageAltText?: Types.Basic.AltText;
  colorCard3Link?: Types.Basic.Link;
  colorCard3LinkText?: React.ReactNode;
  colorCard3Paragraph?: React.ReactNode;
  colorCard4HeadlineTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  colorCard4HeadlineText?: React.ReactNode;
  colorCard4Icon?: Types.Asset.Image;
  colorCard4IconAltText?: Types.Basic.AltText;
  colorCard4Image?: Types.Asset.Image;
  colorCard4ImageAltText?: Types.Basic.AltText;
  colorCard4Link?: Types.Basic.Link;
  colorCard4LinkText?: React.ReactNode;
  colorCard4Paragraph?: React.ReactNode;
  optionsColorCardColor?: "Light" | "Dark";
}): React.JSX.Element;
