import * as React from "react";
import * as Types from "../webflow_modules/types";

declare function Main9CardsSectionWithIcon(props: {
  card1Card1Icon?: React.ReactNode;
  card1Card1Link?: React.ReactNode;
  card1CardParagraphText?: React.ReactNode;
  card1CardVisibility?: Types.Visibility.VisibilityConditions;
  card2Card2Icon?: React.ReactNode;
  card2Card2Link?: React.ReactNode;
  card2CardHeadlineText?: React.ReactNode;
  card2CardParagraphText?: React.ReactNode;
  card3Card3Icon?: React.ReactNode;
  card3Card3Link?: React.ReactNode;
  card3CardHeadlineText?: React.ReactNode;
  card3CardParagraphText?: React.ReactNode;
  card4Card4Icon?: React.ReactNode;
  card4Card4Link?: React.ReactNode;
  card4CardHeadlineText?: React.ReactNode;
  card4CardParagraphText?: React.ReactNode;
  card5Card5Icon?: React.ReactNode;
  card5Card5Link?: React.ReactNode;
  card5CardHeadlineText?: React.ReactNode;
  card5CardParagraphText?: React.ReactNode;
  card6Card6Icon?: React.ReactNode;
  card6Card6Link?: React.ReactNode;
  card6CardHeadlineText?: React.ReactNode;
  card6CardParagraphText?: React.ReactNode;
  card7Card7Icon?: React.ReactNode;
  card7Card7Link?: React.ReactNode;
  card7CardHeadlineText?: React.ReactNode;
  card7CardParagraphText?: React.ReactNode;
  card8Card8Icon?: React.ReactNode;
  card8Card8Link?: React.ReactNode;
  card8CardHeadlineText?: React.ReactNode;
  card8CardParagraphText?: React.ReactNode;
  card9Card9Icon?: React.ReactNode;
  card9Card9Link?: React.ReactNode;
  card9CardHeadlineText?: React.ReactNode;
  card9CardParagraphText?: React.ReactNode;
  mainOverviewButton1?: React.ReactNode;
  mainOverviewButton2?: React.ReactNode;
  mainOverviewHeadline?: React.ReactNode;
  settingsSectionId?: string;
  settingsSectionVisibility?: Types.Visibility.VisibilityConditions;
}): React.JSX.Element;
