import * as React from "react";
import * as Types from "../webflow_modules/types";

declare function UnknownComponent6FeatureCardsWithButton(props: {
  buttonButtonId?: string;
  buttonButtonVisibility?: Types.Visibility.VisibilityConditions;
  buttonColor?: unknown;
  buttonLabelText?: React.ReactNode;
  buttonTypeSize?: unknown;
  card1HeadlineTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  card1HeadlineText?: React.ReactNode;
  card1Icon?: Types.Asset.Image;
  card1IconAltText?: Types.Basic.AltText;
  card1ParagraphText?: React.ReactNode;
  card2HeadlineTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  card2HeadlineText?: React.ReactNode;
  card2Icon?: Types.Asset.Image;
  card2IconAltText?: Types.Basic.AltText;
  card2ParagraphText?: React.ReactNode;
  card3HeadlineTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  card3HeadlineText?: React.ReactNode;
  card3Icon?: Types.Asset.Image;
  card3IconAltText?: Types.Basic.AltText;
  card3ParagraphText?: React.ReactNode;
  card4HeadlineTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  card4HeadlineText?: React.ReactNode;
  card4Icon?: Types.Asset.Image;
  card4IconAltText?: Types.Basic.AltText;
  card4ParagraphText?: React.ReactNode;
  card5HeadlineTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  card5HeadlineText?: React.ReactNode;
  card5Icon?: Types.Asset.Image;
  card5IconAltText?: Types.Basic.AltText;
  card5ParagraphText?: React.ReactNode;
  card6HeadlineTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  card6HeadlineText?: React.ReactNode;
  card6Icon?: Types.Asset.Image;
  card6IconAltText?: Types.Basic.AltText;
  card6ParagraphText?: React.ReactNode;
  headlineEyebrowText?: React.ReactNode;
  headlineHeadlineTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  headlineHeadlineText?: React.ReactNode;
  settingsSectionId?: string;
  settingsSectionVisibility?: Types.Visibility.VisibilityConditions;
}): React.JSX.Element;
